/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
import model.Car;
import model.Uber;

/**
 *
 * @author akshatajadhav
 */
public class MainJFrame extends javax.swing.JFrame {
    
    Uber uber;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        uber = new Uber();
        MainJPanel mjp = new MainJPanel(mainUIPanel, uber);
        mainUIPanel.add("MainJPanel",mjp);
        CardLayout card = (CardLayout) mainUIPanel.getLayout();
        card.next(mainUIPanel);
        pack();
        setLocationRelativeTo(null);
        loadCars();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainUIPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainUIPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainUIPanel;
    // End of variables declaration//GEN-END:variables
    

    private void loadCars() {
        String line = "";
        String splitBy = ",";
        SimpleDateFormat f = new SimpleDateFormat("MM/dd/yyyy");
        f.setLenient(false);
        try {
            File file = new File("HardCodedData.csv");
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                line = myReader.nextLine();
                String[] data = line.split(splitBy);
                Long sn = null;
                int my = 0, seats = 0;
                Date emc = null;
                boolean availbility = false;
                try {
                    sn = Long.parseLong(data[0]);
                    my = Integer.parseInt(data[3]);
                    seats = Integer.parseInt(data[5]);
                    emc = f.parse(data[8]);
                } catch (NumberFormatException | ParseException e) {
                    continue;
                }
                if (data[6].equalsIgnoreCase("true")) {
                    availbility = true;
                }
                Car car = new Car();
                car.setSerialNumber(sn);
                car.setModelNumber(data[1]);
                car.setMake(data[2]);
                car.setManufacturedYear(my);
                car.setType(data[4]);
                car.setSeats(seats);
                car.setAvailability(availbility);
                car.setCity(data[7]);
                car.setMaintenanceCertificateDate(emc);

                if (uber.getSerialNumbers() == null || !uber.getSerialNumbers().contains(sn)) {
                    uber.addCarToFleet(car);
                } 
            }
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
        }
        if(!uber.getCars().isEmpty()){
            uber.setLastModified(new Date());
        }
    }

}
